[project]
title = "Sample Data Dashboard"
version = "0.1.0"
port = 8501
slug = "sample-dashboard"
entrypoint = "sample_dashboard.py"

[branding]
name = "Sample Data Dashboard"       
# logo = "images/logo.png"         
# favicon = "images/favicon.ico"  
primaryColor = "#4CAF50"

[data.sample_csv]
type = "csv"
path = "data/sample.csv"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
